//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AES.Web.SecurityService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecurityService.ISecuritySvc")]
    public interface ISecuritySvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecuritySvc/ValidateUser", ReplyAction="http://tempuri.org/ISecuritySvc/ValidateUserResponse")]
        AES.SecuritySvc.Contracts.ApplicantInfoContract ValidateUser(AES.SecuritySvc.Contracts.ApplicantInfoContract userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecuritySvc/ValidateUser", ReplyAction="http://tempuri.org/ISecuritySvc/ValidateUserResponse")]
        System.Threading.Tasks.Task<AES.SecuritySvc.Contracts.ApplicantInfoContract> ValidateUserAsync(AES.SecuritySvc.Contracts.ApplicantInfoContract userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecuritySvc/GetUser", ReplyAction="http://tempuri.org/ISecuritySvc/GetUserResponse")]
        AES.SecuritySvc.Contracts.ApplicantInfoContract GetUser(AES.SecuritySvc.Contracts.ApplicantInfoContract user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecuritySvc/GetUser", ReplyAction="http://tempuri.org/ISecuritySvc/GetUserResponse")]
        System.Threading.Tasks.Task<AES.SecuritySvc.Contracts.ApplicantInfoContract> GetUserAsync(AES.SecuritySvc.Contracts.ApplicantInfoContract user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecuritySvcChannel : AES.Web.SecurityService.ISecuritySvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecuritySvcClient : System.ServiceModel.ClientBase<AES.Web.SecurityService.ISecuritySvc>, AES.Web.SecurityService.ISecuritySvc {
        
        public SecuritySvcClient() {
        }
        
        public SecuritySvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecuritySvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecuritySvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecuritySvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AES.SecuritySvc.Contracts.ApplicantInfoContract ValidateUser(AES.SecuritySvc.Contracts.ApplicantInfoContract userInfo) {
            return base.Channel.ValidateUser(userInfo);
        }
        
        public System.Threading.Tasks.Task<AES.SecuritySvc.Contracts.ApplicantInfoContract> ValidateUserAsync(AES.SecuritySvc.Contracts.ApplicantInfoContract userInfo) {
            return base.Channel.ValidateUserAsync(userInfo);
        }
        
        public AES.SecuritySvc.Contracts.ApplicantInfoContract GetUser(AES.SecuritySvc.Contracts.ApplicantInfoContract user) {
            return base.Channel.GetUser(user);
        }
        
        public System.Threading.Tasks.Task<AES.SecuritySvc.Contracts.ApplicantInfoContract> GetUserAsync(AES.SecuritySvc.Contracts.ApplicantInfoContract user) {
            return base.Channel.GetUserAsync(user);
        }
    }
}
